version: '3.8'
services:
  app:
    build: .
    ports:
      - '80:3000'
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
  redis:
    image: redis:7
    ports:
      - '6379:6379'
